version: '3.7'
services: 
  archon-ui:
    container_name: archon_ui
    build:
      context: .
      dockerfile: Dockerfile
    image: p3solutions/archon-ui:3.1
    expose: 
        - 80
    ports:
        - 80:80
    volumes:
        - type: bind
          source: /etc/letsencrypt
          target: /etc/letsencrypt
        - type: bind
          source: /home/ubuntu/sslKeyJava
          target: /ssl_path
    networks:
        - archon-network
    env_file: archon-ui.env

networks:
    archon-network:
        driver: bridge
